{{- if .Values.ca.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hlf-ca--ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{- range $i, $org := .Values.PeerOrgs }}
  - host: hlf-ca-{{ $org.Name | lower }}.{{ $.Values.ingress.parentDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: hlf-ca--{{ $org.Name | lower }}
            port: 
              number: 7054
{{- end }}
  tls:
  - hosts:
{{- range $i, $org := .Values.PeerOrgs }}
    - hlf-ca-{{ $org.Name | lower }}.{{ $.Values.ingress.parentDomain }}
{{- end }}
    secretName: hlf-ca--ingress-tls
{{- end }} {{- /* if ingress.enabled */ -}}
