{{- range $i, $org := .Values.PeerOrgs }}
{{- range $peerIndex := until ($org.Template.Count | int) }}
{{- range $i, $peerCouchDB := $.Values.couchdbAccount }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}
{{- $peerDomain := (printf "%s.%s" $peer $org.Domain) }}
{{- if eq $peerCouchDB.domain $peerDomain }}

apiVersion: v1
kind: Service
metadata:
  name: hlf-couchdb--{{ $org.Name | lower }}--{{ $peer | lower }}
  labels:
    name: hlf-couchdb--{{ $org.Name | lower }}--{{ $peer | lower }}
spec:
  type: NodePort
  selector:
    app: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}
  ports:
  - protocol: TCP
    port: 5984
    nodePort: {{ $peerCouchDB.port | int }}
    name: couchdb
---
{{- end }} {{- /* If CouchDB */ -}} 
{{- end }} {{- /* COuchDB */ -}} 
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}
