{{- if $.Values.enabledPostgres }}
{{- $org := index $.Values.PeerOrgs 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-explorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-app
  template:
    metadata:
      labels:
        app: explorer-app
    spec:
      volumes:
      - name: fabric-tool-storage
        persistentVolumeClaim:
          claimName: fabric-tool-pv-claim
      - name: peer-{{ $org.Name | lower }}-admin-msp
        secret:
          secretName: hlf-peer--{{ $org.Name | lower }}--admin-msp
          items:
          - key: config.yaml
            path: config.yaml
          - key: cert.pem
            path: signcerts/cert.pem
          - key: key.pem
            path: keystore/key.pem
          - key: cacert.pem
            path: cacerts/ca.{{ $org.Domain }}-cert.pem
          - key: tlscacert.pem
            path: tlscacerts/cert.pem
      - name: peer-{{ $org.Name | lower }}-peer0-tls
        secret:
          secretName: hlf-peer--{{ $org.Name | lower }}--peer0-tls
          items:
          - key: ca.crt
            path: ca.crt
      - name: orderer-tlsca
        secret:
          secretName: hlf-orderer--orderer-tlsca

      containers:
      - name: explorer
        image: hyperledger/explorer:latest
        imagePullPolicy: Always
        command: ["bash", "-c", ""chmod +x /fabric-storage/explorer-config/run-explorer-app.sh && /fabric-storage/explorer-config/run-explorer-app.sh"]
        env:
        - name: DATABASE_HOST
          value: blockchain-explorer-db
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /fabric-storage
          name: fabric-tool-storage
        - mountPath: /etc/hyperledger/fabric/msp/
          name: peer-{{ $org.Name | lower }}-admin-msp
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-{{ $org.Name | lower }}-peer0-tls
        - mountPath: /hlf_config/orderer-tlsca
          name: orderer-tlsca
{{- end }}
