{{- $org := index $.Values.PeerOrgs 0 }}
{{- $peerAddress := $.Values.useActualDomains | ternary (printf "peer0.%s:7051" $org.Domain) (printf "hlf-peer--%s--peer0:7051" ($org.Name | lower)) }}
apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: fabric-tool-storage
    persistentVolumeClaim:
      claimName: fabric-tool-pv-claim
  - name: peer-{{ $org.Name | lower }}-admin-msp
    secret:
      secretName: hlf-peer--{{ $org.Name | lower }}--admin-msp
      items:
      - key: config.yaml
        path: config.yaml
      - key: cert.pem
        path: signcerts/cert.pem
      - key: key.pem
        path: keystore/key.pem
      - key: cacert.pem
        path: cacerts/ca.{{ $org.Domain }}-cert.pem
      - key: tlscacert.pem
        path: tlscacerts/cert.pem
  - name: orderer-tlsca
    secret:
      secretName: hlf-orderer--orderer-tlsca
  - name: peer-{{ $org.Name | lower }}-peer0-tls
    secret:
      secretName: hlf-peer--{{ $org.Name | lower }}--peer0-tls
  
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:2.2
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      volumeMounts:
        - mountPath: /fabric-storage
          name: fabric-tool-storage
        - mountPath: /etc/hyperledger/fabric/msp/
          name: peer-{{ $org.Name | lower }}-admin-msp
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-{{ $org.Name | lower }}-peer0-tls
        - mountPath: /hlf_config/orderer-tlsca
          name: orderer-tlsca
        
      env:
        - name: CORE_PEER_ADDRESS
          value: {{ $peerAddress }}
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_PEER_LOCALMSPID
          value: {{ $org.Name }}MSP
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt

