orgs:
  - Name: Org1
    Domain: org1.example.com
    PeerCount: 2
    UserCount: 1
  - Name: Org2
    Domain: org2.example.com
    PeerCount: 2
    UserCount: 1
  - Name: Org3
    Domain: org3.example.com
    PeerCount: 2
    UserCount: 1