apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-explorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-app
  template:
    metadata:
      labels:
        app: explorer-app
    spec:
      volumes:
      - name: chaincodes-pv-storage
        persistentVolumeClaim:
          claimName: chaincodes-pv-claim
      - name: peer-org1-admin-msp
        secret:
          secretName: hlf-peer--org1--admin-msp
          items:
          - key: config.yaml
            path: config.yaml
          - key: cert.pem
            path: signcerts/cert.pem
          - key: key.pem
            path: keystore/key.pem
          - key: cacert.pem
            path: cacerts/ca.org1.example.com-cert.pem
          - key: tlscacert.pem
            path: tlscacerts/cert.pem
      - name: peer-org1-peer0-tls
        secret:
          secretName: hlf-peer--org1--peer0-tls
          items:
          - key: ca.crt
            path: ca.crt

      containers:
      - name: explorer
        image: hyperledger/explorer:latest
        imagePullPolicy: Always
        command: ["sh", "-c", "sleep 48h"]
        env:
        - name: DATABASE_HOST
          value: blockchain-explorer-db
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /data
          name: chaincodes-pv-storage
        - mountPath: /etc/hyperledger/fabric/admin-msp/
          name: peer-org1-admin-msp
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-org1-peer0-tls
