apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: chaincodes-pv-storage
    persistentVolumeClaim:
      claimName: chaincodes-pv-claim
  - name: peer-org1-admin-msp
    secret:
      secretName: hlf-peer--org1--admin-msp
      items:
      - key: config.yaml
        path: config.yaml
      - key: cert.pem
        path: signcerts/cert.pem
      - key: key.pem
        path: keystore/key.pem
      - key: cacert.pem
        path: cacerts/ca.org1.example.com-cert.pem
      - key: tlscacert.pem
        path: tlscacerts/cert.pem
  - name: peer-org1-peer0-tls
    secret:
      secretName: hlf-peer--org1--peer0-tls
      items:
      - key: ca.crt
        path: ca.crt
  
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:2.2
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]

      volumeMounts:
        - mountPath: /data
          name: chaincodes-pv-storage
        - mountPath: /etc/hyperledger/fabric/admin-msp/
          name: peer-org1-admin-msp
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-org1-peer0-tls
      env:
        - name: CORE_PEER_ADDRESS
          value: hlf-peer--org1--peer0:7051
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt

