---
Organizations:
    - &${ORG_NAME_UPPER}
        Name: ${ORG_NAME_UPPER}MSP
        ID: ${ORG_NAME_UPPER}MSP

        MSPDir: ../../../organizations/peerOrganizations/${ORG_NAME}.blocktrace.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('${ORG_NAME_UPPER}MSP.admin', '${ORG_NAME_UPPER}MSP.peer', '${ORG_NAME_UPPER}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${ORG_NAME_UPPER}MSP.admin', '${ORG_NAME_UPPER}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${ORG_NAME_UPPER}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${ORG_NAME_UPPER}MSP.peer')"
        AnchorPeers:
            - Host: peer0.${ORG_NAME}.blocktrace.com
              Port: ${ORG_PORT}