chaincodes:
{{- range $i, $chaincode := .Values.chaincodes }}
  - name: {{ $chaincode.Name }}
    # if defined, this will override the global chaincode.version value
    version: # "2.0" 
    # chaincode will be installed to all peers in these organizations
    orgs: [
{{- range $i, $orgName := $chaincode.Orgs }}
      {{- if $i }}, {{- end }}
      {{- $orgName }}
{{- end }}]
    # at which channels are we instantiating/upgrading chaincode?
    channels:
    - name: {{ $chaincode.Channel }}
      # chaincode will be instantiated/upgraded using the first peer in the first organization
      # chaincode will be invoked on all peers in these organizations
      orgs: [
{{- range $i, $orgName := $chaincode.Orgs }}
      {{- if $i }}, {{- end }}
      {{- $orgName }}
{{- end }}]
      policy: OR(
{{- range $i, $orgName := $chaincode.Orgs }}
      {{- if $i }}, {{- end }}
      {{- printf "%s%s" $orgName "MSP.member" | quote }}
{{- end }})
{{- end }}